#!/bin/sh

# Regenerate SSH keys for _this_ host
rm /etc/ssh/ssh_host*key*

# On debian-like systems, use dpkg reconfigre, else restart directly
if [ -x /usr/sbin/dpkg-reconfigure ] ; then
    dpkg-reconfigure -fnoninteractive -pcritical openssh-server
else
    /etc/init.d/ssh restart
fi
